# Generated by Django 4.0.8 on 2022-10-23 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test01',
            options={'managed': True},
        ),
    ]
