# Generated by Django 4.0.8 on 2022-10-23 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test01', '0002_alter_test01_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test01',
            options={'managed': False},
        ),
    ]
